#!/bin/sh

file=$0
fileC=${file}.C
fileRUN=${file}.run

ROOTLIBS="-L/usr/lib64 `$ROOTSYS/bin/root-config --glibs` -lMathCore -lMinuit"
ROOTINCDIR=`$ROOTSYS/bin/root-config --incdir`

BASETREEDIR="../src"

rm -f ${fileRUN}

echo "[variableComparisonPlots]: Compiling"
rootcling -f MuonPogTreeDict.C -c ${BASETREEDIR}/MuonPogTree.h ${BASETREEDIR}/MuonPogTreeLinkDef.h

g++ -g -std=gnu++11 -I${ROOTINCDIR} ${fileC} MuonPogTreeDict.C ${ROOTLIBS} -lX11 -lboost_system -lboost_filesystem -o ${fileRUN}

echo "[invariantMassPlots]: Running with parameters $@" 
${fileRUN} $@

rm -f MuonPogTreeDict.C MuonPogTreeDict.h MuonPogTreeDict_rdict.pcm
